# Generated by Django 5.0.3 on 2024-03-17 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=4, unique=True)),
                ('established', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('jersey_number', models.CharField(max_length=3)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField(help_text='Weight (in pounds)')),
                ('position', models.CharField(max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='player_analysis_app.team')),
            ],
        ),
    ]
