# Generated by Django 5.0.3 on 2024-03-18 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('mpg', models.DecimalField(decimal_places=2, help_text='Minutes per game', max_digits=5)),
                ('pts', models.DecimalField(decimal_places=2, help_text='Points per game', max_digits=5)),
                ('fgm', models.IntegerField(help_text='Field Goals Made')),
                ('fga', models.IntegerField(help_text='Field Goals Attempted')),
                ('fg_pct', models.DecimalField(decimal_places=2, help_text='Field Goal Percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('threepm', models.IntegerField(help_text='3 Points Made')),
                ('threepa', models.IntegerField(help_text='3 Points Attempted')),
                ('three_pct', models.DecimalField(decimal_places=2, help_text='3 Point Percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ftm', models.IntegerField(help_text='Free Throws Made')),
                ('fta', models.IntegerField(help_text='Free Throws Attempted')),
                ('ft_pct', models.DecimalField(decimal_places=2, help_text='Free Throw Percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('oreb', models.IntegerField(help_text='Offensive Rebounds')),
                ('dreb', models.IntegerField(help_text='Defensive Rebounds')),
                ('reb', models.IntegerField(help_text='Total Rebounds')),
                ('ast', models.IntegerField(help_text='Assists')),
                ('tov', models.IntegerField(help_text='Turnovers')),
                ('stl', models.IntegerField(help_text='Steals')),
                ('blk', models.IntegerField(help_text='Blocks')),
                ('pf', models.IntegerField(help_text='Personal Fouls')),
                ('plus_minus', models.IntegerField(help_text='+/-')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='player_analysis_app.player')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
